# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import name_node_pb2 as name__node__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in name_node_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NameNodeStub(object):
    """============================
    Servicio del NameNode
    ============================
    Expone RPCs (métodos remotos) que los clientes pueden invocar.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PlanFileWrite = channel.unary_unary(
                '/griddfs.NameNode/PlanFileWrite',
                request_serializer=name__node__pb2.PlanFileWriteRequest.SerializeToString,
                response_deserializer=name__node__pb2.PlanFileWriteResponse.FromString,
                _registered_method=True)


class NameNodeServicer(object):
    """============================
    Servicio del NameNode
    ============================
    Expone RPCs (métodos remotos) que los clientes pueden invocar.
    """

    def PlanFileWrite(self, request, context):
        """Planifica la escritura de un archivo:
        - El cliente envía: nombre de archivo y tamaño total en bytes.
        - El NameNode responde: tamaño de bloque, número de bloques y
        asignación de DataNodes por cada bloque (para replicación/colocación).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NameNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PlanFileWrite': grpc.unary_unary_rpc_method_handler(
                    servicer.PlanFileWrite,
                    request_deserializer=name__node__pb2.PlanFileWriteRequest.FromString,
                    response_serializer=name__node__pb2.PlanFileWriteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'griddfs.NameNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('griddfs.NameNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NameNode(object):
    """============================
    Servicio del NameNode
    ============================
    Expone RPCs (métodos remotos) que los clientes pueden invocar.
    """

    @staticmethod
    def PlanFileWrite(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/griddfs.NameNode/PlanFileWrite',
            name__node__pb2.PlanFileWriteRequest.SerializeToString,
            name__node__pb2.PlanFileWriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
