# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: data_node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'data_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x61ta_node.proto\x12\x07griddfs\"\xaf\x01\n\x12UploadBlockRequest\x12*\n\x05start\x18\x01 \x01(\x0b\x32\x19.griddfs.UploadBlockStartH\x00\x12#\n\x05\x63hunk\x18\x02 \x01(\x0b\x32\x12.griddfs.DataChunkH\x00\x12,\n\x06\x63ommit\x18\x03 \x01(\x0b\x32\x1a.griddfs.UploadBlockCommitH\x00\x12\x13\n\tfile_name\x18\x04 \x01(\tH\x00\x42\x05\n\x03msg\"^\n\x10UploadBlockStart\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x15\n\rexpected_size\x18\x02 \x01(\x04\x12\x0e\n\x06sha256\x18\x03 \x01(\t\x12\x11\n\tfile_name\x18\x04 \x01(\t\"\x19\n\tDataChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"L\n\x11UploadBlockCommit\x12\x15\n\rexpected_size\x18\x01 \x01(\x04\x12\x0e\n\x06sha256\x18\x02 \x01(\t\x12\x10\n\x08\x66inalize\x18\x03 \x01(\x08\"W\n\x11UploadBlockResult\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x13\n\x0bstored_size\x18\x03 \x01(\x04\x12\x12\n\nblock_path\x18\x04 \x01(\t\"H\n\x14\x44ownloadBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x0e\n\x06length\x18\x03 \x01(\x04\"&\n\x12\x44\x65leteBlockRequest\x12\x10\n\x08\x62lock_id\x18\x01 \x01(\t\"\x0f\n\rHealthRequest\";\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04node\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\" \n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x97\x02\n\x08\x44\x61taNode\x12J\n\x0bUploadBlock\x12\x1b.griddfs.UploadBlockRequest\x1a\x1a.griddfs.UploadBlockResult\"\x00(\x01\x12\x46\n\rDownloadBlock\x12\x1d.griddfs.DownloadBlockRequest\x1a\x12.griddfs.DataChunk\"\x00\x30\x01\x12:\n\x0b\x44\x65leteBlock\x12\x1b.griddfs.DeleteBlockRequest\x1a\x0c.griddfs.Ack\"\x00\x12;\n\x06Health\x12\x16.griddfs.HealthRequest\x1a\x17.griddfs.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADBLOCKREQUEST']._serialized_start=29
  _globals['_UPLOADBLOCKREQUEST']._serialized_end=204
  _globals['_UPLOADBLOCKSTART']._serialized_start=206
  _globals['_UPLOADBLOCKSTART']._serialized_end=300
  _globals['_DATACHUNK']._serialized_start=302
  _globals['_DATACHUNK']._serialized_end=327
  _globals['_UPLOADBLOCKCOMMIT']._serialized_start=329
  _globals['_UPLOADBLOCKCOMMIT']._serialized_end=405
  _globals['_UPLOADBLOCKRESULT']._serialized_start=407
  _globals['_UPLOADBLOCKRESULT']._serialized_end=494
  _globals['_DOWNLOADBLOCKREQUEST']._serialized_start=496
  _globals['_DOWNLOADBLOCKREQUEST']._serialized_end=568
  _globals['_DELETEBLOCKREQUEST']._serialized_start=570
  _globals['_DELETEBLOCKREQUEST']._serialized_end=608
  _globals['_HEALTHREQUEST']._serialized_start=610
  _globals['_HEALTHREQUEST']._serialized_end=625
  _globals['_HEALTHRESPONSE']._serialized_start=627
  _globals['_HEALTHRESPONSE']._serialized_end=686
  _globals['_ACK']._serialized_start=688
  _globals['_ACK']._serialized_end=720
  _globals['_DATANODE']._serialized_start=723
  _globals['_DATANODE']._serialized_end=1002
# @@protoc_insertion_point(module_scope)
