# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: name_node.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'name_node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fname_node.proto\x12\x07griddfs\"<\n\x14PlanFileWriteRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_size\x18\x02 \x01(\x04\"9\n\x0f\x42lockAssignment\x12\x13\n\x0b\x62lock_index\x18\x01 \x01(\x04\x12\x11\n\tdatanodes\x18\x02 \x03(\t\"n\n\x15PlanFileWriteResponse\x12\x12\n\nblock_size\x18\x01 \x01(\x04\x12\x12\n\nnum_blocks\x18\x02 \x01(\x04\x12-\n\x0b\x61ssignments\x18\x03 \x03(\x0b\x32\x18.griddfs.BlockAssignment2\\\n\x08NameNode\x12P\n\rPlanFileWrite\x12\x1d.griddfs.PlanFileWriteRequest\x1a\x1e.griddfs.PlanFileWriteResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'name_node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANFILEWRITEREQUEST']._serialized_start=28
  _globals['_PLANFILEWRITEREQUEST']._serialized_end=88
  _globals['_BLOCKASSIGNMENT']._serialized_start=90
  _globals['_BLOCKASSIGNMENT']._serialized_end=147
  _globals['_PLANFILEWRITERESPONSE']._serialized_start=149
  _globals['_PLANFILEWRITERESPONSE']._serialized_end=259
  _globals['_NAMENODE']._serialized_start=261
  _globals['_NAMENODE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
